# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      before_install:
        - sudo timedatectl set-timezone Asia/Taipei  # Set timezone to Taiwan
        - sudo apt-get install texlive-fonts-extra
        - sudo apt install libmagick++-dev
        - bash update-data-raw.sh                    # Renew internal data
#    - os: osx
#      osx_image: xcode7.3
#      pandoc: false
#      before_install:
#        - curl -fLo /tmp/pandoc-1.12-1.dmg https://github.com/jgm/pandoc/releases/download/1.12/pandoc-1.12-1.dmg
#        - sudo hdiutil attach /tmp/pandoc-1.12-1.dmg -mountpoint /Volumes/pandoc
#        - sudo installer -pkg "/Volumes/pandoc/pandoc-1.12.pkg" -allowUntrusted -target /
#        - sudo hdiutil detach /Volumes/pandoc
#      env: PANDOC='mac-cran'

r_github_packages:
  - r-lib/covr
  - r-lib/pkgdown

after_success:
  - Rscript -e 'covr::codecov()'
  - bash update-data-raw.sh

before_deploy:
  - bash deploy.sh
#  - [ -f pttR*.tar.gz ] && rm pttR*.tar.gz 


# deploy docs/ and master branch to branch 'gh-pages' & 'win-build'
deploy:
  - provider: pages    # Deploy master to branch build
    target-branch: build  
    skip-cleanup: true
    github-token: $GH_TOKEN_win  # Set in travis-ci.org dashboard
    keep-history: false
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
  - provider: pages    # Deploy master/docs to branch gh-pages
    skip-cleanup: true
    github-token: $GH_TOKEN  
    keep-history: false
    local-dir: docs    # Web output directory
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
