# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
  - linux
  - osx

after_success:
  - Rscript -e 'pkgdown::build_site()'

# deplot docs/ to branch 'gh-pages'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
  keep-history: true
  local-dir: docs          # Web output directory
  on:
    branch: master
